### ISSUE TITLE
Kerberos  authentication

### ISSUE THREAD

**Issue by jjfarrell** [genepi/cloudgene#8]
After submitting a vcf for imputation on cloudgene,   The following error occurs:

org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]

The log is below.  This hadoop cluster is using Kerberos for authentication.  Can ImputationServer be configured to authenticate with Kerberos?

There is also a warning that the _Cluster seems unreachable. Hadoop support disabled_.   Is this related? Any suggestions? 

```
./cloudgene server  --user farrell  --conf /usr/hdp/2.4.0.0-169/hadoop/conf

Cloudgene 1.30.3
http://www.cloudgene.io
(c) 2009-2018 Lukas Forer and Sebastian Schoenherr
Built by travis on 2018-02-12T14:59:50Z

Use Haddop configuration folder /usr/hdp/2.4.0.0-169/hadoop/conf with username farrell
18/05/26 19:44:55 INFO mapred.Main: Cloudgene 1.30.3
18/05/26 19:44:55 INFO mapred.Main: Built by travis on 2018-02-12T14:59:50Z
18/05/26 19:44:55 INFO mapred.Main: Establish connection successful
18/05/26 19:44:55 INFO mapred.Main: Database is uptodate.
18/05/26 19:44:55 INFO util.Fixtures: User admin already exists.
18/05/26 19:44:55 INFO util.Fixtures: Template MAINTENANCE_MESSAGE already exists.
18/05/26 19:44:55 INFO util.Fixtures: Template FOOTER already exists.
18/05/26 19:44:55 INFO util.Fixtures: Template REGISTER_MAIL already exists.
18/05/26 19:44:55 INFO util.Fixtures: Template RETIRE_JOB_MAIL already exists.
18/05/26 19:44:55 INFO util.Fixtures: Template RECOVERY_MAIL already exists.
18/05/26 19:44:55 INFO jobs.PersistentWorkflowEngine: Init Counters....
18/05/26 19:44:55 INFO mapred.Main: Starting web server at port 8082
18/05/26 19:44:55 INFO mapred.WebServer: Start CronJobScheduler...
[WARN]  Cluster seems unreachable. Hadoop support disabled.
[WARN]  Docker not found. Docker support disabled.

Server is running on http://localhost:8082

Please press ctrl-c to stop.
18/05/26 19:45:08 INFO LogService: 2018-05-26   19:45:08        10.48.225.55    -       10.48.225.55    8082    GET     /api/v2/server/apps/genepi-imputationserver     -       200     2973    0       341     http://scc-hadoop.bu.edu:8082   Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0     http://scc-hadoop.bu.edu:8082/start.html
 Parsed: refpanel
 Parsed: mode
 Parsed: check1
 Parsed: aesEncryption
 Parsed: check2
 Parsed: job-name
 Parsed: r2Filter
 Parsed: build
 Parsed: phasing
 Parsed: files
 Parsed: tool
 Parsed: population
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
...

**Comment by jjfarrell** [comment]
The latest version 2.0.0 RC6 now recognizes the local hadoop cluster when server is started.
